name: iman_invest
description: "Iman Invest internship project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.3
  fancy_field_new: ^0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.16
  geolocator: ^9.0.2
  get_it: ^7.2.0
  http: ^1.2.2
  injectable: ^1.5.0
  location: ^7.0.1
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  very_good_analysis: ^7.0.0
  yandex_mapkit: ^3.2.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.0



flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 100

  assets:
    - assets/
    - .env
